/*The database was created in SQL server Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64) Express Edition (64-bit)*/

--Create DataBase--

SET NOCOUNT ON
GO

USE MASTER
GO

IF EXISTS (SELECT * FROM SYSDATABASES WHERE NAME = 'BogTrPoll')
	DROP DATABASE BogTrPoll
IF EXISTS (SELECT [name] FROM master.sys.sql_logins WHERE [name] = 'ReadUserBTP')
BEGIN
	DROP LOGIN ReadUserBTP
END
IF EXISTS(SELECT [name] FROM master.sys.sysusers WHERE [name] = 'ReadUserBTP')
BEGIN
	DROP USER ReadUserBTP
END
GO

DECLARE @project_directory NVARCHAR(200) = 'C:\Users\felip\Documents\BogotaTransportOverview\' -- Change this location to your project folder ubication

EXEC (N'CREATE DATABASE BogTrPoll
	ON PRIMARY (NAME = N''BogTrPoll'', FILENAME = N''' + @project_directory + N'BogTrPoll_DataBase\Database\bogtrpoll.mdf'')
	LOG ON (NAME = N''BogTrPoll_log'',  FILENAME = N''' + @project_directory  + N'BogTrPoll_DataBase\Database\bogtrpoll.ldf'')')
GO

USE BogTrPoll
GO

--Create Reading User--

CREATE LOGIN ReadUserBTP WITH PASSWORD = 'Reader123$'

CREATE USER ReadUserBTP FOR LOGIN ReadUserBTP
EXEC sp_addrolemember N'db_datareader', N'ReadUserBTP'
GO

--Build the Structure--

CREATE TABLE ACTIVIDAD 
(
	ID NUMERIC(2,0) NOT NULL,
	ACTIVIDAD_PRINCIPAL NVARCHAR(255) NULL,
	CONSTRAINT id_actividad_pk PRIMARY KEY CLUSTERED (ID)
)
GO

CREATE TABLE ACTIVIDADECONOMICA
(
	ID NUMERIC(2,0) NOT NULL,
	ACTIVIDAD_ECONOMICA NVARCHAR(255) NULL,
	CONSTRAINT id_actividadeconomica_pk PRIMARY KEY CLUSTERED (ID)
)
GO

CREATE TABLE AGRESIONFISICA
(
	ID NUMERIC(2,0) NOT NULL,
	DESCRIPCION NVARCHAR(70) NULL,
	CONSTRAINT id_agresionfisica_pk PRIMARY KEY CLUSTERED (ID)
)
GO

CREATE TABLE AGRESIONSEXUAL
(
	ID NUMERIC(2,0) NOT NULL,
	DESCRIPCION NVARCHAR(150) NULL,
	CONSTRAINT id_agresionsexual_pk PRIMARY KEY CLUSTERED (ID)
)
GO

CREATE TABLE BENEFICIOSITP
(
	ID NUMERIC(1,0) NOT NULL,
	DESCRIPCION NVARCHAR(50) NULL,
	CONSTRAINT id_beneficiositp_pk PRIMARY KEY CLUSTERED (ID)
)
GO

CREATE TABLE CONTACTOS
(
	CODIGO INT NOT NULL,
	DEFINICION NVARCHAR(64) NULL,
	CONSTRAINT id_contactos_pk PRIMARY KEY CLUSTERED (CODIGO)
)
GO

CREATE TABLE CULTURA
(
	ID NUMERIC(2,0) NOT NULL,
	CULTURA NVARCHAR(50) NULL,
	CONSTRAINT id_cultura_pk PRIMARY KEY CLUSTERED (ID)
)
GO

CREATE TABLE CURSOLICENCIA
(
	ID NUMERIC(1,0) NOT NULL,
	DESCRIPCION NVARCHAR(255) NULL,
	CONSTRAINT id_cursolicencia_pk PRIMARY KEY CLUSTERED (ID)
)
GO

CREATE TABLE DEPARTAMENTO
(
	ID INT NOT NULL,
	NOMBRE NVARCHAR(350) NULL,
	CONSTRAINT id_departamento_pk PRIMARY KEY CLUSTERED (ID)
)
GO

CREATE TABLE DISPONIBILIDAD_VEHICULOS
(
	ID_ENCUESTA INT NOT NULL,
	ID_VEHICULO NUMERIC(2,0) NOT NULL,
	CANTIDAD NUMERIC(2,0) NULL,
	FACTOR_EXP_CAL TEXT NULL,
	CONSTRAINT id_disponibilidad_pk PRIMARY KEY CLUSTERED (ID_ENCUESTA, ID_VEHICULO)
)
GO

CREATE TABLE RANGOINGRESOS
(
	ID INT NOT NULL,
	DESCRIPCION NVARCHAR(50) NOT NULL,
	CONSTRAINT id_rangoingresos_pk PRIMARY KEY CLUSTERED (ID)
)
GO

CREATE TABLE TIPOVIVIENDA
(
	ID NUMERIC(1, 0) NOT NULL,
	DESCRIPCION NVARCHAR(20) NOT NULL,
	CONSTRAINT id_tipovivienda_pk PRIMARY KEY CLUSTERED (ID)
)
GO

CREATE TABLE VIVIENDAPROPIA
(
	ID NUMERIC(1, 0) NOT NULL,
	DESCRIPCION NVARCHAR(50) NOT NULL,
	CONSTRAINT id_viviendapropia_pk PRIMARY KEY CLUSTERED (ID)
)
GO

CREATE TABLE ENCUESTAS
(
	ID_ENCUESTA INT NOT NULL,
	BARRIO NVARCHAR(255) NULL,
	ID_TIPOVIVIENDA NUMERIC(1, 0) NOT NULL,
	ID_VIVIENDAPROPIA NUMERIC(1, 0) NOT NULL,
	NUMERO_HOGARES INT NULL,
	NUMERO_PERSONAS NUMERIC(2, 0) DEFAULT 0 NULL,
	PUNTAJE_SISBEN NUMERIC(10, 0) NULL,
	ID_BENEFICIOSITP NUMERIC(1, 0) NULL,
	FECHA_UPLOAD SMALLDATETIME NULL,
	DURACION NVARCHAR(20) NULL,
	ENCUESTA_COMPLETA NVARCHAR(15) NULL,
	UTCDIF INT NULL,
	ENCUESTADOR_FECHA DATE NULL,
	ENCUESTADOR_HORA NVARCHAR(30) NULL,
	ESTRATO_ENERGIA NUMERIC(1, 0) NULL,
	ESTRATO_ACUEDUCTO NUMERIC(1, 0) NULL,
	ESTRATO_ALCANTARILLADO NUMERIC(1, 0) NULL,
	ESTRATO_RECOLECCION_BASURAS NUMERIC(1, 0) NULL,
	ESTRATO_GAS_NATURAL NUMERIC(1, 0) NULL,
	ID_BENEFICIOSITP2 NUMERIC(1, 0) NULL,
	ID_BENEFICIOSITP3 NUMERIC(1, 0) NULL,
	ID_BENEFICIOSITP4 INT NULL,
	PERSONA1HOGAR INT NULL,
	PERSONA2HOGAR INT NULL,
	PERSONA3HOGAR INT NULL,
	PERSONA4HOGAR INT NULL,
	PERSONA5HOGAR INT NULL,
	PERSONA6HOGAR INT NULL,
	PERSONA7HOGAR INT NULL,
	PERSONA8HOGAR INT NULL,
	PERSONA9HOGAR INT NULL,
	SUPERVISION INT NULL,
	HORA_FIN NVARCHAR(30) NULL,
	FINALIZADA INT NULL,
	SRV_ENERGIA NUMERIC(2, 0) NULL,
	SRV_ACUEDUCTO NUMERIC(1, 0) NULL,
	SRV_ALCANTARILLADO NUMERIC(1, 0) NULL,
	SRV_RECOLECCION_BASURAS NUMERIC(1, 0) NULL,
	SRV_GAS_NATURAL NUMERIC(1, 0) NULL,
	FECHA_PROCESO_BD NVARCHAR(70) NULL,
	COMPLETA_TELEFONICAMENTE INT NULL,
	ID_RANGOINGRESOS INT NULL,
	VEHIC_PERSONAIDONEA INT NULL,
	DIA_SEMANA NVARCHAR(20) NULL,
	ENCUESTAS_SISBEN INT NULL,
	CLASIFICACION_SISBEN INT NULL,
	LATITUD_HOGAR NUMERIC(20, 15) NULL,
	LONGITUD_HOGAR NUMERIC(20, 15) NULL,
	ZAT_HOGAR INT NULL,
	PONDERADOR_CALIBRADO TEXT NULL,
	ESTRATO INT NULL,
	FACTOR_AJUSTE NUMERIC(20, 15) NULL,
	PI_K_I NUMERIC(20, 15) NULL,
	PI_K_II NUMERIC(20, 15) NULL,
	PI_K_III NUMERIC(20, 15) NULL,
	FE_TOTAL NUMERIC(20, 15) NULL,
	ID_MANZANA NVARCHAR(20) NULL,
	ID_MUNICIPIO INT NULL,
	CONSTRAINT id_encuestas_pk PRIMARY KEY CLUSTERED (ID_ENCUESTA),
	CONSTRAINT fk_encuestas_tipovivienda FOREIGN KEY (ID_TIPOVIVIENDA) REFERENCES dbo.TIPOVIVIENDA(ID),
	CONSTRAINT fk_encuestas_viviendapropia FOREIGN KEY (ID_VIVIENDAPROPIA) REFERENCES dbo.VIVIENDAPROPIA(ID),
	CONSTRAINT fk_encuestas_beneficiositp FOREIGN KEY (ID_BENEFICIOSITP) REFERENCES dbo.BENEFICIOSITP(ID),
	CONSTRAINT fk_encuestas_rangoingresos FOREIGN KEY (ID_RANGOINGRESOS) REFERENCES dbo.RANGOINGRESOS(ID),
)
GO
 CREATE  INDEX idx_encuestas ON dbo.ENCUESTAS(ID_MANZANA)
GO
 CREATE  INDEX idx_encuestas_0 ON dbo.ENCUESTAS(ID_TIPOVIVIENDA)
GO
 CREATE  INDEX idx_encuestas_1 ON dbo.ENCUESTAS(ID_VIVIENDAPROPIA)
GO
 CREATE  INDEX idx_encuestas_2 ON dbo.ENCUESTAS(ZAT_HOGAR)
GO
 CREATE  INDEX idx_encuestas_5 ON dbo.ENCUESTAS(ID_BENEFICIOSITP)
GO
 CREATE  INDEX idx_encuestas_6 ON dbo.ENCUESTAS(ID_RANGOINGRESOS)
GO


CREATE TABLE EXENTO_PP
(
	ID NUMERIC(2, 0) NOT NULL,
	DESCRIPCION NVARCHAR(50) NULL,
	CONSTRAINT id_exento_pp_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE LICENCIACONDUCCION
(
	ID NUMERIC(1, 0) NOT NULL,
	DESCRIPCION NVARCHAR(70) NULL,
	CONSTRAINT id_licenciaconduccion_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE LIMITACIONFISICA
(
	ID NUMERIC(2, 0) NOT NULL,
	LIMITACION NVARCHAR(255) NULL,
	CONSTRAINT id_limitacionfisica_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE LUGARAGRESION
(
	ID NUMERIC(2, 0) NOT NULL,
	DESCRIPCION NVARCHAR(70) NULL,
	CONSTRAINT id_lugaragresion_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE LUGARPARQUEO
(
	ID NUMERIC(2, 0) NOT NULL,
	DESCRIPCION NVARCHAR(50) NULL,
	CONSTRAINT id_lugarparqueo_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE MEDIO_PREDOMINANTE
(
	CODIGO NVARCHAR(15) NULL,
	NOMBRE NVARCHAR(30) NULL,
	PREDOMINANCIA INT NOT NULL,
	CONSTRAINT id_medio_predominante_pk PRIMARY KEY CLUSTERED (PREDOMINANCIA)
)
GO


CREATE TABLE MEDIOTRASPORTE
(
	ID NUMERIC(2, 0) NOT NULL,
	DESCRIPCION NVARCHAR(100) NULL,
	CONSTRAINT id_mediotrasporte_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE MOTIVONOVEHICULO
(
	ID NUMERIC(2, 0) NOT NULL,
	DESCRIPCION NVARCHAR(70) NULL,
	CONSTRAINT id_motivonovehiculo_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE MOTIVOVIAJE
(
	ID NUMERIC(2, 0) NOT NULL,
	DESCRIPCION NVARCHAR(70) NULL,
	CONSTRAINT id_motivoviaje_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE MUNICIPIO
(
	ID NUMERIC(14, 0) NOT NULL,
	ID_DEPARTAMENTO INT NULL,
	NOMBRE NVARCHAR(350) NOT NULL,
	CODIGO_DANE TEXT NULL,
	CONSTRAINT id_municipio_pk PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT fk_municipio_departamento FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID)
)
GO


CREATE TABLE NIVELEDUCATIVO
(
	ID NUMERIC(2, 0) NOT NULL,
	NIVEL_EDUCATIVO NVARCHAR(255) NULL,
	CONSTRAINT id_niveleducativo_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE NOBICICLETA
(
	ID NUMERIC(2, 0) NOT NULL,
	DESCRIPCION NVARCHAR(70) NULL,
	CONSTRAINT id_nobicicleta_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE PARENTESCO
(
	ID NUMERIC(2, 0) NOT NULL,
	NOMBRE NVARCHAR(50) NULL,
	CONSTRAINT id_parentesco_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE SEXO
(
	ID NUMERIC(1, 0) NOT NULL,
	SEXO NVARCHAR(255) NULL,
	CONSTRAINT id_sexo_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE TIPOAGRESION
(
	ID NUMERIC(2, 0) NOT NULL,
	DESCRIPCION NVARCHAR(70) NULL,
	CONSTRAINT id_tipoagresion_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE TIPOCOMBUSTIBLE
(
	ID NUMERIC(2, 0) NOT NULL,
	DESCRIPCION NVARCHAR(20) NULL,
	CONSTRAINT id_tipocombustible_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE TIPOVEHICULO
(
	ID NUMERIC(2, 0) NOT NULL,
	DESCRIPCION NVARCHAR(60) NULL,
	CONSTRAINT id_tipovehiculo_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE TRABAJOACTIVIDAD
(
	ID INT NOT NULL,
	NOMBRE NVARCHAR(40) NULL,
	CONSTRAINT id_trabajoactividad_pk PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE PERSONAS
(
	ID_ENCUESTA INT NOT NULL,
	NUMERO_PERSONA NUMERIC(2, 0) NOT NULL,
	ID_PARENTESCO NUMERIC(2, 0) NULL,
	ID_SEXO NUMERIC(1, 0) NULL,
	EDAD NUMERIC(3, 0) NULL,
	ID_CULTURA NUMERIC(2, 0) NULL,
	ID_NIVELEDUCATIVO NUMERIC(2, 0) NULL,
	ID_ACTIVIDAD NUMERIC(2, 0) NULL,
	ID_ACTIVIDADECONOMICA NUMERIC(2, 0) NULL,
	ASISTE_INSTITUCIONEDUCATIVA INT NULL,
	NUMERO_EMPLEOS NUMERIC(3, 0) NULL,
	LIMITACION_FISICA NUMERIC(2, 0) NULL,
	ID_LIMITACIONFISICA NUMERIC(2, 0) NULL,
	ID_LIMITACIONFISICA2 NUMERIC(2, 0) NULL,
	ID_LIMITACIONFISICA3 NUMERIC(2, 0) NULL,
	ID_MEDIOTRANSPORTE3 NUMERIC(2, 0) NULL,
	ID_MEDIOTRANSPORTE2 NUMERIC(2, 0) NULL,
	ID_MEDIOTRANSPORTE NUMERIC(2, 0) NULL,
	ID_CURSOLICENCIA4 NUMERIC(1, 0) NULL,
	ID_CURSOLICENCIA3 NUMERIC(1, 0) NULL,
	ID_CURSOLICENCIA2 NUMERIC(1, 0) NULL,
	ID_CURSOLICENCIA NUMERIC(1, 0) NULL,
	REALIZO_DESPLAZAMIENTO INT NULL,
	TRABAJO_CASA INT NULL,
	USO_VEHICULOPRIVADO NUMERIC(2, 0) NULL,
	ID_MOTIVONOVEHICULO NUMERIC(2, 0) NULL,
	MOVILIZA_BICICLETA NUMERIC(1, 0) NULL,
	ID_NOBICICLETA1 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA2 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA3 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA4 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA5 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA6 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA7 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA8 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA9 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA10 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA11 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA12 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA13 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA14 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA15 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA16 NUMERIC(2, 0) NULL,
	ID_NOBICICLETA17 NUMERIC(2, 0) NULL,
	REACCION_AUTORIDAD INT NULL,
	ID_TIPOAGRESION1 NUMERIC(2, 0) NULL,
	ID_TIPOAGRESION2 NUMERIC(2, 0) NULL,
	ID_TIPOAGRESION3 NUMERIC(2, 0) NULL,
	ID_TIPOAGRESION4 NUMERIC(2, 0) NULL,
	ID_TIPOAGRESION5 NUMERIC(2, 0) NULL,
	ID_TIPOAGRESION6 NUMERIC(2, 0) NULL,
	ID_TIPOAGRESION7 NUMERIC(2, 0) NULL,
	ID_TIPOAGRESION8 NUMERIC(2, 0) NULL,
	ID_AGRESIONFISICA3 NUMERIC(2, 0) NULL,
	ID_AGRESIONFISICA4 NUMERIC(2, 0) NULL,
	ID_AGRESIONFISICA5 NUMERIC(2, 0) NULL,
	ID_AGRESIONFISICA2 NUMERIC(2, 0) NULL,
	ID_AGRESIONFISICA1 NUMERIC(2, 0) NULL,
	ID_AGRESIONSEXUAL2 NUMERIC(2, 0) NULL,
	ID_AGRESIONSEXUAL1 NUMERIC(2, 0) NULL,
	ID_AGRESIONSEXUAL3 NUMERIC(2, 0) NULL,
	ID_AGRESIONSEXUAL4 NUMERIC(2, 0) NULL,
	ID_LUGARAGRESION NUMERIC(2, 0) NULL,
	ID_TRABAJOACTIVIDAD INT NULL,
	ID_LICENCIACONDUCCION1 NUMERIC(1, 0) NULL,
	ID_LICENCIACONDUCCION2 NUMERIC(1, 0) NULL,
	ID_LICENCIACONDUCCION3 NUMERIC(1, 0) NULL,
	ID_LICENCIACONDUCCION4 NUMERIC(1, 0) NULL,
	VICTIMA_AGRESION INT NULL,
	REG_ANTIGUO NUMERIC(1, 0) DEFAULT 0 NULL,
	PONDERADOR_CALIBRADO TEXT NULL,
	FACTOR_AJUSTE NUMERIC(20, 15) NULL,
	PI_K_I NUMERIC(20, 15) NULL,
	PI_K_II NUMERIC(20, 15) NULL,
	PI_K_III NUMERIC(20, 15) NULL,
	FE_TOTAL NUMERIC(20, 15) NULL,
	CONSTRAINT id_personas_pk PRIMARY KEY CLUSTERED (ID_ENCUESTA, NUMERO_PERSONA),
	CONSTRAINT fk_personas FOREIGN KEY (ID_ENCUESTA) REFERENCES ENCUESTAS(ID_ENCUESTA),
	CONSTRAINT fk_personas_nobicicleta1 FOREIGN KEY (ID_NOBICICLETA1) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta2 FOREIGN KEY (ID_NOBICICLETA2) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta3 FOREIGN KEY (ID_NOBICICLETA3) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta4 FOREIGN KEY (ID_NOBICICLETA4) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta5 FOREIGN KEY (ID_NOBICICLETA5) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta6 FOREIGN KEY (ID_NOBICICLETA6) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta7 FOREIGN KEY (ID_NOBICICLETA7) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta8 FOREIGN KEY (ID_NOBICICLETA8) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta9 FOREIGN KEY (ID_NOBICICLETA9) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta10 FOREIGN KEY (ID_NOBICICLETA10) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta11 FOREIGN KEY (ID_NOBICICLETA11) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta12 FOREIGN KEY (ID_NOBICICLETA12) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta13 FOREIGN KEY (ID_NOBICICLETA13) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta14 FOREIGN KEY (ID_NOBICICLETA14) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta15 FOREIGN KEY (ID_NOBICICLETA15) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta16 FOREIGN KEY (ID_NOBICICLETA16) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_nobicicleta17 FOREIGN KEY (ID_NOBICICLETA17) REFERENCES NOBICICLETA(ID),
	CONSTRAINT fk_personas_motivovehiculo FOREIGN KEY (ID_MOTIVONOVEHICULO) REFERENCES MOTIVONOVEHICULO(ID),
	CONSTRAINT fk_personas_parentesco FOREIGN KEY (ID_PARENTESCO) REFERENCES PARENTESCO(ID),
	CONSTRAINT fk_personas_sexo FOREIGN KEY (ID_SEXO) REFERENCES SEXO(ID),
	CONSTRAINT fk_personas_cultura FOREIGN KEY (ID_CULTURA) REFERENCES CULTURA(ID),
	CONSTRAINT fk_personas_niveleducativo FOREIGN KEY (ID_NIVELEDUCATIVO) REFERENCES NIVELEDUCATIVO(ID),
	CONSTRAINT fk_personas_actividadeconomica FOREIGN KEY (ID_ACTIVIDADECONOMICA) REFERENCES ACTIVIDADECONOMICA(ID),
	CONSTRAINT fk_personas_actividad FOREIGN KEY (ID_ACTIVIDAD) REFERENCES ACTIVIDAD(ID),
	CONSTRAINT fk_personas_limitacionfisica FOREIGN KEY (ID_LIMITACIONFISICA) REFERENCES LIMITACIONFISICA(ID),
	CONSTRAINT fk_personas_limitacionfisica2 FOREIGN KEY (ID_LIMITACIONFISICA2) REFERENCES LIMITACIONFISICA(ID),
	CONSTRAINT fk_personas_limitacionfisica3 FOREIGN KEY (ID_LIMITACIONFISICA3) REFERENCES LIMITACIONFISICA(ID),
	CONSTRAINT fk_personas_cursolicencia FOREIGN KEY (ID_CURSOLICENCIA) REFERENCES CURSOLICENCIA(ID),
	CONSTRAINT fk_personas_cursolicencia2 FOREIGN KEY (ID_CURSOLICENCIA2) REFERENCES CURSOLICENCIA(ID),
	CONSTRAINT fk_personas_cursolicencia3 FOREIGN KEY (ID_CURSOLICENCIA3) REFERENCES CURSOLICENCIA(ID),
	CONSTRAINT fk_personas_cursolicencia4 FOREIGN KEY (ID_CURSOLICENCIA4) REFERENCES CURSOLICENCIA(ID),
	CONSTRAINT fk_personas_mediotransporte FOREIGN KEY (ID_MEDIOTRANSPORTE) REFERENCES MEDIOTRASPORTE(ID),
	CONSTRAINT fk_personas_mediotransporte2 FOREIGN KEY (ID_MEDIOTRANSPORTE2) REFERENCES MEDIOTRASPORTE(ID),
	CONSTRAINT fk_personas_mediotransporte3 FOREIGN KEY (ID_MEDIOTRANSPORTE3) REFERENCES MEDIOTRASPORTE(ID),
	CONSTRAINT fk_personas_tipoagresion1 FOREIGN KEY (ID_TIPOAGRESION1) REFERENCES TIPOAGRESION(ID),
	CONSTRAINT fk_personas_tipoagresion2 FOREIGN KEY (ID_TIPOAGRESION2) REFERENCES TIPOAGRESION(ID),
	CONSTRAINT fk_personas_tipoagresion3 FOREIGN KEY (ID_TIPOAGRESION3) REFERENCES TIPOAGRESION(ID),
	CONSTRAINT fk_personas_tipoagresion4 FOREIGN KEY (ID_TIPOAGRESION4) REFERENCES TIPOAGRESION(ID),
	CONSTRAINT fk_personas_tipoagresion5 FOREIGN KEY (ID_TIPOAGRESION5) REFERENCES TIPOAGRESION(ID),
	CONSTRAINT fk_personas_tipoagresion6 FOREIGN KEY (ID_TIPOAGRESION6) REFERENCES TIPOAGRESION(ID),
	CONSTRAINT fk_personas_tipoagresion7 FOREIGN KEY (ID_TIPOAGRESION7) REFERENCES TIPOAGRESION(ID),
	CONSTRAINT fk_personas_tipoagresion8 FOREIGN KEY (ID_TIPOAGRESION8) REFERENCES TIPOAGRESION(ID),
	CONSTRAINT fk_personas_agresionfisica1 FOREIGN KEY (ID_AGRESIONFISICA1) REFERENCES AGRESIONFISICA(ID),
	CONSTRAINT fk_personas_agresionfisica2 FOREIGN KEY (ID_AGRESIONFISICA2) REFERENCES AGRESIONFISICA(ID),
	CONSTRAINT fk_personas_agresionfisica3 FOREIGN KEY (ID_AGRESIONFISICA3) REFERENCES AGRESIONFISICA(ID),
	CONSTRAINT fk_personas_agresionfisica4 FOREIGN KEY (ID_AGRESIONFISICA4) REFERENCES AGRESIONFISICA(ID),
	CONSTRAINT fk_personas_agresionfisica5 FOREIGN KEY (ID_AGRESIONFISICA5) REFERENCES AGRESIONFISICA(ID),
	CONSTRAINT fk_personas_agresionsexual1 FOREIGN KEY (ID_AGRESIONSEXUAL1) REFERENCES AGRESIONSEXUAL(ID),
	CONSTRAINT fk_personas_agresionsexual2 FOREIGN KEY (ID_AGRESIONSEXUAL2) REFERENCES AGRESIONSEXUAL(ID),
	CONSTRAINT fk_personas_agresionsexual3 FOREIGN KEY (ID_AGRESIONSEXUAL3) REFERENCES AGRESIONSEXUAL(ID),
	CONSTRAINT fk_personas_agresionsexual4 FOREIGN KEY (ID_AGRESIONSEXUAL4) REFERENCES AGRESIONSEXUAL(ID),
	CONSTRAINT fk_personas_lugaragresion FOREIGN KEY (ID_LUGARAGRESION) REFERENCES LUGARAGRESION(ID),
	CONSTRAINT fk_personas_trabajoactividad FOREIGN KEY (ID_TRABAJOACTIVIDAD) REFERENCES TRABAJOACTIVIDAD(ID),
	CONSTRAINT fk_personas_licenciaconduccion1 FOREIGN KEY (ID_LICENCIACONDUCCION1) REFERENCES LICENCIACONDUCCION(ID),
	CONSTRAINT fk_personas_licenciaconduccion2 FOREIGN KEY (ID_LICENCIACONDUCCION2) REFERENCES LICENCIACONDUCCION(ID),
	CONSTRAINT fk_personas_licenciaconduccion3 FOREIGN KEY (ID_LICENCIACONDUCCION3) REFERENCES LICENCIACONDUCCION(ID),
	CONSTRAINT fk_personas_licenciaconduccion4 FOREIGN KEY (ID_LICENCIACONDUCCION4) REFERENCES LICENCIACONDUCCION(ID),
)
GO
CREATE INDEX idx_personas ON dbo.PERSONAS(ID_NOBICICLETA1)
GO
CREATE INDEX idx_personas_0 ON dbo.PERSONAS(ID_NOBICICLETA2)
GO
CREATE INDEX idx_personas_1 ON dbo.PERSONAS(ID_NOBICICLETA3)
GO
CREATE INDEX idx_personas_2 ON dbo.PERSONAS(ID_NOBICICLETA4)
GO
CREATE INDEX idx_personas_3 ON dbo.PERSONAS(ID_NOBICICLETA5)
GO
CREATE INDEX idx_personas_4 ON dbo.PERSONAS(ID_NOBICICLETA6)
GO
CREATE INDEX idx_personas_5 ON dbo.PERSONAS(ID_NOBICICLETA7)
GO
CREATE INDEX idx_personas_6 ON dbo.PERSONAS(ID_NOBICICLETA8)
GO
CREATE INDEX idx_personas_7 ON dbo.PERSONAS(ID_NOBICICLETA9)
GO
CREATE INDEX idx_personas_8 ON dbo.PERSONAS(ID_NOBICICLETA10)
GO
CREATE INDEX idx_personas_9 ON dbo.PERSONAS(ID_NOBICICLETA11)
GO
CREATE INDEX idx_personas_10 ON dbo.PERSONAS(ID_NOBICICLETA12)
GO
CREATE INDEX idx_personas_11 ON dbo.PERSONAS(ID_NOBICICLETA13)
GO
CREATE INDEX idx_personas_12 ON dbo.PERSONAS(ID_NOBICICLETA14)
GO
CREATE INDEX idx_personas_13 ON dbo.PERSONAS(ID_NOBICICLETA15)
GO
CREATE INDEX idx_personas_14 ON dbo.PERSONAS(ID_NOBICICLETA16)
GO
CREATE INDEX idx_personas_15 ON dbo.PERSONAS(ID_NOBICICLETA17)
GO
CREATE INDEX idx_personas_16 ON dbo.PERSONAS(ID_MOTIVONOVEHICULO)
GO
CREATE INDEX idx_personas_17 ON dbo.PERSONAS(ID_PARENTESCO)
GO
CREATE INDEX idx_personas_18 ON dbo.PERSONAS(ID_SEXO)
GO
CREATE INDEX idx_personas_19 ON dbo.PERSONAS(ID_CULTURA)
GO
CREATE INDEX idx_personas_20 ON dbo.PERSONAS(ID_NIVELEDUCATIVO)
GO
CREATE INDEX idx_personas_21 ON dbo.PERSONAS(ID_ACTIVIDADECONOMICA)
GO
CREATE INDEX idx_personas_22 ON dbo.PERSONAS(ID_ACTIVIDAD)
GO
CREATE INDEX idx_personas_23 ON dbo.PERSONAS(ID_LIMITACIONFISICA)
GO
CREATE INDEX idx_personas_24 ON dbo.PERSONAS(ID_LIMITACIONFISICA2)
GO
CREATE INDEX idx_personas_25 ON dbo.PERSONAS(ID_LIMITACIONFISICA3)
GO
CREATE INDEX idx_personas_26 ON dbo.PERSONAS(ID_CURSOLICENCIA)
GO
CREATE INDEX idx_personas_27 ON dbo.PERSONAS(ID_CURSOLICENCIA2)
GO
CREATE INDEX idx_personas_28 ON dbo.PERSONAS(ID_CURSOLICENCIA3)
GO
CREATE INDEX idx_personas_29 ON dbo.PERSONAS(ID_CURSOLICENCIA4)
GO
CREATE INDEX idx_personas_30 ON dbo.PERSONAS(ID_MEDIOTRANSPORTE)
GO
CREATE INDEX idx_personas_31 ON dbo.PERSONAS(ID_MEDIOTRANSPORTE2)
GO
CREATE INDEX idx_personas_32 ON dbo.PERSONAS(ID_MEDIOTRANSPORTE3)
GO
CREATE INDEX idx_personas_33 ON dbo.PERSONAS(ID_TIPOAGRESION1)
GO
CREATE INDEX idx_personas_34 ON dbo.PERSONAS(ID_TIPOAGRESION2)
GO
CREATE INDEX idx_personas_35 ON dbo.PERSONAS(ID_TIPOAGRESION3)
GO
CREATE INDEX idx_personas_36 ON dbo.PERSONAS(ID_TIPOAGRESION4)
GO
CREATE INDEX idx_personas_37 ON dbo.PERSONAS(ID_TIPOAGRESION5)
GO
CREATE INDEX idx_personas_38 ON dbo.PERSONAS(ID_TIPOAGRESION6)
GO
CREATE INDEX idx_personas_39 ON dbo.PERSONAS(ID_TIPOAGRESION7)
GO
CREATE INDEX idx_personas_40 ON dbo.PERSONAS(ID_TIPOAGRESION8)
GO
CREATE INDEX idx_personas_41 ON dbo.PERSONAS(ID_AGRESIONFISICA1)
GO
CREATE INDEX idx_personas_42 ON dbo.PERSONAS(ID_AGRESIONFISICA2)
GO
CREATE INDEX idx_personas_43 ON dbo.PERSONAS(ID_AGRESIONFISICA3)
GO
CREATE INDEX idx_personas_44 ON dbo.PERSONAS(ID_AGRESIONFISICA4)
GO
CREATE INDEX idx_personas_45 ON dbo.PERSONAS(ID_AGRESIONFISICA5)
GO
CREATE INDEX idx_personas_46 ON dbo.PERSONAS(ID_AGRESIONSEXUAL1)
GO
CREATE INDEX idx_personas_47 ON dbo.PERSONAS(ID_AGRESIONSEXUAL2)
GO
CREATE INDEX idx_personas_48 ON dbo.PERSONAS(ID_AGRESIONSEXUAL3)
GO
CREATE INDEX idx_personas_49 ON dbo.PERSONAS(ID_AGRESIONSEXUAL4)
GO
CREATE INDEX idx_personas_50 ON dbo.PERSONAS(ID_LUGARAGRESION)
GO
CREATE INDEX idx_personas_51 ON dbo.PERSONAS(ID_TRABAJOACTIVIDAD)
GO
CREATE INDEX idx_personas_52 ON dbo.PERSONAS(ID_LICENCIACONDUCCION1)
GO
CREATE INDEX idx_personas_53 ON dbo.PERSONAS(ID_LICENCIACONDUCCION2)
GO
CREATE INDEX idx_personas_54 ON dbo.PERSONAS(ID_LICENCIACONDUCCION3)
GO
CREATE INDEX idx_personas_55 ON dbo.PERSONAS(ID_LICENCIACONDUCCION4)
GO

CREATE TABLE VIAJES1
(
	ID_ENCUESTA INT,
	NUMERO_PERSONA NUMERIC(2, 0),
	NUMERO_VIAJE NUMERIC(2, 0),
	ID_MOTIVOVIAJE NUMERIC(2, 0),
	ID_MUNICIPIO_DESTINO NUMERIC(14, 0),
	TIEMPO_CAMINO INT,
	HORA_INICIO TIME,
	HORA_FIN TIME,
	ID_MEDIO_PREDOMINANTE INT,
	ZAT_DESTINO INT,
	ZAT_ORIGEN INT,
	ID_MUNICIPIO_ORIGEN NUMERIC(14, 0),
	LATITUD_ORIGEN NUMERIC(20, 15),
	LATITUD_DESTINO NUMERIC(20, 15),
	LONGITUD_ORIGEN NUMERIC(20, 15),
	LONGITUD_DESTINO NUMERIC(20, 15),
	IMPUTACION BIT DEFAULT 0,
	DIFERENCIA_HORAS TIME,
	ID INT,
	FACTOR_AJUSTE NUMERIC(20, 15),
	PONDERADOR_CALIBRADO NUMERIC(20, 15),
	DIA_HABIL INT,
	DIA_NOHABIL INT,
	PICO_HABIL INT,
	PICO_NOHABIL INT,
	VALLE_NOHABIL INT,
	VALLE_HABIL INT,
	PI_K_I NUMERIC(20, 15),
	PI_K_II NUMERIC(20, 15),
	PI_K_III NUMERIC(20, 15),
	FE_TOTAL NUMERIC(20, 15),
	FACTOR_AJUSTE_TRANSMILENIO NUMERIC(20, 15),
	PONDERADOR_CALIBRADO_VIAJES NUMERIC(20, 15),
)
GO
CREATE TABLE VIAJES2
(
	ID_ENCUESTA INT,
	NUMERO_PERSONA NUMERIC(2, 0),
	NUMERO_VIAJE NUMERIC(2, 0),
	ID_MOTIVOVIAJE NUMERIC(2, 0),
	ID_MUNICIPIO_DESTINO NUMERIC(14, 0),
	TIEMPO_CAMINO INT,
	HORA_INICIO TIME,
	HORA_FIN TIME,
	ID_MEDIO_PREDOMINANTE INT,
	ZAT_DESTINO INT,
	ZAT_ORIGEN INT,
	ID_MUNICIPIO_ORIGEN NUMERIC(14, 0),
	LATITUD_ORIGEN NUMERIC(20, 15),
	LATITUD_DESTINO NUMERIC(20, 15),
	LONGITUD_ORIGEN NUMERIC(20, 15),
	LONGITUD_DESTINO NUMERIC(20, 15),
	IMPUTACION BIT DEFAULT 0,
	DIFERENCIA_HORAS TIME,
	ID INT,
	FACTOR_AJUSTE NUMERIC(20, 15),
	PONDERADOR_CALIBRADO NUMERIC(20, 15),
	DIA_HABIL INT,
	DIA_NOHABIL INT,
	PICO_HABIL INT,
	PICO_NOHABIL INT,
	VALLE_NOHABIL INT,
	VALLE_HABIL INT,
	PI_K_I NUMERIC(20, 15),
	PI_K_II NUMERIC(20, 15),
	PI_K_III NUMERIC(20, 15),
	FE_TOTAL NUMERIC(20, 15),
	FACTOR_AJUSTE_TRANSMILENIO NUMERIC(20, 15),
	PONDERADOR_CALIBRADO_VIAJES NUMERIC(20, 15),
)
GO
CREATE TABLE VIAJES
(
	ID_ENCUESTA INT,
	NUMERO_PERSONA NUMERIC(2, 0),
	NUMERO_VIAJE NUMERIC(2, 0),
	ID_MOTIVOVIAJE NUMERIC(2, 0),
	ID_MUNICIPIO_DESTINO NUMERIC(14, 0),
	TIEMPO_CAMINO INT,
	HORA_INICIO TIME,
	HORA_FIN TIME,
	ID_MEDIO_PREDOMINANTE INT,
	ZAT_DESTINO INT,
	ZAT_ORIGEN INT,
	ID_MUNICIPIO_ORIGEN NUMERIC(14, 0),
	LATITUD_ORIGEN NUMERIC(20, 15),
	LATITUD_DESTINO NUMERIC(20, 15),
	LONGITUD_ORIGEN NUMERIC(20, 15),
	LONGITUD_DESTINO NUMERIC(20, 15),
	IMPUTACION BIT DEFAULT 0,
	DIFERENCIA_HORAS TIME,
	ID INT,
	FACTOR_AJUSTE NUMERIC(20, 15),
	PONDERADOR_CALIBRADO NUMERIC(20, 15),
	DIA_HABIL INT,
	DIA_NOHABIL INT,
	PICO_HABIL INT,
	PICO_NOHABIL INT,
	VALLE_NOHABIL INT,
	VALLE_HABIL INT,
	PI_K_I NUMERIC(20, 15),
	PI_K_II NUMERIC(20, 15),
	PI_K_III NUMERIC(20, 15),
	FE_TOTAL NUMERIC(20, 15),
	FACTOR_AJUSTE_TRANSMILENIO NUMERIC(20, 15),
	PONDERADOR_CALIBRADO_VIAJES NUMERIC(20, 15),
	CONSTRAINT viajes_pk PRIMARY KEY CLUSTERED (ID_ENCUESTA, NUMERO_PERSONA, NUMERO_VIAJE, ID_MOTIVOVIAJE),
	CONSTRAINT fk_viajes FOREIGN KEY (ID_ENCUESTA, NUMERO_PERSONA) REFERENCES dbo.PERSONAS(ID_ENCUESTA, NUMERO_PERSONA),
	CONSTRAINT fk_viajes_0 FOREIGN KEY (ID_MOTIVOVIAJE) REFERENCES dbo.MOTIVOVIAJE(ID),
	CONSTRAINT fk_viajes_municipio_destino FOREIGN KEY (ID_MUNICIPIO_DESTINO) REFERENCES dbo.MUNICIPIO(ID),
	CONSTRAINT fk_viajes_municipio_origen FOREIGN KEY (ID_MUNICIPIO_ORIGEN) REFERENCES dbo.MUNICIPIO(ID),
	CONSTRAINT fk_viajes_medio_predominante FOREIGN KEY (ID_MEDIO_PREDOMINANTE) REFERENCES dbo.MEDIO_PREDOMINANTE(PREDOMINANCIA)
)
GO
CREATE INDEX idx_viajes ON dbo.VIAJES(ID_ENCUESTA, NUMERO_PERSONA)
GO
CREATE INDEX idx_viajes_0 ON dbo.VIAJES(ID_MOTIVOVIAJE)
GO
CREATE INDEX idx_viajes_1 ON dbo.VIAJES(ID_MUNICIPIO_DESTINO)
GO
CREATE INDEX idx_viajes_2 ON dbo.VIAJES(ID_MEDIO_PREDOMINANTE)
GO
CREATE INDEX idx_viajes_3 ON dbo.VIAJES(ID_MUNICIPIO_ORIGEN)
GO

CREATE TABLE ETAPAS1
(
	ID_ENCUESTA INT NOT NULL,
	NUMERO_PERSONA NUMERIC(2, 0) NOT NULL,
	NUMERO_VIAJE NUMERIC(2, 0) NOT NULL,
	NUMERO_ETAPA NUMERIC(2, 0) NOT NULL,
	ID_MEDIOTRASPORTE NUMERIC(2, 0) NULL,
	ID_MINUCIPIO NUMERIC(2, 0) NULL,
	MINUTOS INTEGER NULL,
	CUADRAS INTEGER NULL,
	MINUTO_ESPERA INTEGER NULL,
	COSTO_PASAJE INTEGER NULL,
	PARADERO NVARCHAR(255) NULL,
	RUTA NVARCHAR(255) NULL,
	VEHICULO_HOGAR INTEGER NULL,
	ESTACION_VEHICULO NVARCHAR(255) NULL,
	CUANTIA_PAGO INTEGER NULL,
	MODALIDAD_PAGO INTEGER NULL,
	DESCENSO NVARCHAR(255) NULL,
	ID_MUNICIPIO_DESCENSO INTEGER NULL,
	IMPUTACION BIT DEFAULT 0 NULL,
	ID BIGINT NULL,
	PONDERADOR_CALIBRADO NUMERIC(20, 15) NULL,
	FACTOR_AJUSTE NUMERIC(20, 15) NULL,
	ETAPAS NUMERIC(20, 15) NULL,
	IDET NVARCHAR(12) NULL,
	PI_K_I NUMERIC(20, 15) NULL,
	PI_K_II NUMERIC(20, 15) NULL,
	PI_K_III NUMERIC(20, 15) NULL,
	FE_TOTAL NUMERIC(20, 15) NULL,
	FACTOR_AJUSTE_TRANSMILENIO NUMERIC(20, 15) NULL,
	PONDERADOR_CALIBRADO_VIAJES NUMERIC(20, 15) NULL,
	CONSTRAINT numero_etapa_chk1 CHECK (NUMERO_ETAPA > 0),
	CONSTRAINT numero_persona_chk1 CHECK (NUMERO_PERSONA > 0),
	CONSTRAINT numero_viaje_chk1 CHECK (NUMERO_VIAJE > 0)
)
GO
CREATE TABLE ETAPAS2
(
	ID_ENCUESTA INT NOT NULL,
	NUMERO_PERSONA NUMERIC(2, 0) NOT NULL,
	NUMERO_VIAJE NUMERIC(2, 0) NOT NULL,
	NUMERO_ETAPA NUMERIC(2, 0) NOT NULL,
	ID_MEDIOTRASPORTE NUMERIC(2, 0) NULL,
	ID_MINUCIPIO NUMERIC(2, 0) NULL,
	MINUTOS INTEGER NULL,
	CUADRAS INTEGER NULL,
	MINUTO_ESPERA INTEGER NULL,
	COSTO_PASAJE INTEGER NULL,
	PARADERO NVARCHAR(255) NULL,
	RUTA NVARCHAR(255) NULL,
	VEHICULO_HOGAR INTEGER NULL,
	ESTACION_VEHICULO NVARCHAR(255) NULL,
	CUANTIA_PAGO INTEGER NULL,
	MODALIDAD_PAGO INTEGER NULL,
	DESCENSO NVARCHAR(255) NULL,
	ID_MUNICIPIO_DESCENSO INTEGER NULL,
	IMPUTACION BIT DEFAULT 0 NULL,
	ID BIGINT NULL,
	PONDERADOR_CALIBRADO NUMERIC(20, 15) NULL,
	FACTOR_AJUSTE NUMERIC(20, 15) NULL,
	ETAPAS NUMERIC(20, 15) NULL,
	IDET NVARCHAR(12) NULL,
	PI_K_I NUMERIC(20, 15) NULL,
	PI_K_II NUMERIC(20, 15) NULL,
	PI_K_III NUMERIC(20, 15) NULL,
	FE_TOTAL NUMERIC(20, 15) NULL,
	FACTOR_AJUSTE_TRANSMILENIO NUMERIC(20, 15) NULL,
	PONDERADOR_CALIBRADO_VIAJES NUMERIC(20, 15) NULL,
	CONSTRAINT numero_etapa_chk2 CHECK (NUMERO_ETAPA > 0),
	CONSTRAINT numero_persona_chk2 CHECK (NUMERO_PERSONA > 0),
	CONSTRAINT numero_viaje_chk2 CHECK (NUMERO_VIAJE > 0)
)
GO
CREATE TABLE ETAPAS
(
	ID_ENCUESTA INT NOT NULL,
	NUMERO_PERSONA NUMERIC(2, 0) NOT NULL,
	NUMERO_VIAJE NUMERIC(2, 0) NOT NULL,
	NUMERO_ETAPA NUMERIC(2, 0) NOT NULL,
	ID_MEDIOTRASPORTE NUMERIC(2, 0) NULL,
	ID_MINUCIPIO NUMERIC(2, 0) NULL,
	MINUTOS INTEGER NULL,
	CUADRAS INTEGER NULL,
	MINUTO_ESPERA INTEGER NULL,
	COSTO_PASAJE INTEGER NULL,
	PARADERO NVARCHAR(255) NULL,
	RUTA NVARCHAR(255) NULL,
	VEHICULO_HOGAR INTEGER NULL,
	ESTACION_VEHICULO NVARCHAR(255) NULL,
	CUANTIA_PAGO INTEGER NULL,
	MODALIDAD_PAGO INTEGER NULL,
	DESCENSO NVARCHAR(255) NULL,
	ID_MUNICIPIO_DESCENSO INTEGER NULL,
	IMPUTACION BIT DEFAULT 0 NULL,
	ID BIGINT NULL,
	PONDERADOR_CALIBRADO NUMERIC(20, 15) NULL,
	FACTOR_AJUSTE NUMERIC(20, 15) NULL,
	ETAPAS NUMERIC(20, 15) NULL,
	IDET NVARCHAR(12) NULL,
	PI_K_I NUMERIC(20, 15) NULL,
	PI_K_II NUMERIC(20, 15) NULL,
	PI_K_III NUMERIC(20, 15) NULL,
	FE_TOTAL NUMERIC(20, 15) NULL,
	FACTOR_AJUSTE_TRANSMILENIO NUMERIC(20, 15) NULL,
	PONDERADOR_CALIBRADO_VIAJES NUMERIC(20, 15) NULL,
	CONSTRAINT id_etapas_pk PRIMARY KEY CLUSTERED (ID_ENCUESTA, NUMERO_PERSONA, NUMERO_VIAJE, NUMERO_ETAPA),
	CONSTRAINT numero_etapa_chk CHECK (NUMERO_ETAPA > 0),
	CONSTRAINT numero_persona_chk CHECK (NUMERO_PERSONA > 0),
	CONSTRAINT numero_viaje_chk CHECK (NUMERO_VIAJE > 0)
)
GO
CREATE INDEX idx_etapas ON dbo.ETAPAS(ID_ENCUESTA, NUMERO_PERSONA, NUMERO_VIAJE)
GO


CREATE TABLE VEHICULOS
(
	ID_ENCUESTA INT NOT NULL,
	ID_VEHICULO INT NOT NULL,
	ID_TIPOVEHICULO NUMERIC(2, 0) NULL,
	ID_COMBUSTIBLE NUMERIC(2, 0) NULL,
	MUNICIPIO_MATRICULA NVARCHAR(64) NULL,
	PERTENECE_VEHICULO NUMERIC(2, 0) NULL,
	PERSONA_DUENOVEHICULO NUMERIC(2, 0) NULL,
	EXENTO_PICOYPLACA NUMERIC(2, 0) NULL,
	RAZON_EXENTO NUMERIC(2, 0) NULL,
	DONDE_GUARDAVEHICULO NUMERIC(2, 0) NULL,
	VALOR_PARQUEO INT NULL,
	CONSTRAINT id_vehiculos PRIMARY KEY CLUSTERED (ID_ENCUESTA, ID_VEHICULO),
	CONSTRAINT fk_vehiculos_encuestas FOREIGN KEY (ID_ENCUESTA) REFERENCES ENCUESTAS(ID_ENCUESTA),
	CONSTRAINT fk_vehiculos_tipovehiculo FOREIGN KEY (ID_TIPOVEHICULO) REFERENCES TIPOVEHICULO(ID),
	CONSTRAINT fk_vehiculos_tipocombustible FOREIGN KEY (ID_COMBUSTIBLE) REFERENCES TIPOCOMBUSTIBLE(ID),
	CONSTRAINT fk_vehiculos_lugarparqueo FOREIGN KEY (DONDE_GUARDAVEHICULO) REFERENCES LUGARPARQUEO(ID),
	CONSTRAINT fk_vehiculos_exentopp FOREIGN KEY (RAZON_EXENTO) REFERENCES EXENTO_PP(ID)
)
GO
CREATE INDEX idx_vehiculos ON dbo.VEHICULOS(ID_ENCUESTA)
GO
CREATE INDEX idx_vehiculos_0 ON dbo.VEHICULOS(ID_TIPOVEHICULO)
GO
CREATE INDEX idx_vehiculos_1 ON dbo.VEHICULOS(ID_COMBUSTIBLE)
GO
CREATE INDEX idx_vehiculos_2 ON dbo.VEHICULOS(DONDE_GUARDAVEHICULO)
GO
CREATE INDEX idx_vehiculos_3 ON dbo.VEHICULOS(RAZON_EXENTO)
GO


CREATE TABLE LOCALIDAD
(
	ID NVARCHAR(2) NOT NULL,
	NOMBRE NVARCHAR(30) NULL,
	CONSTRAINT id_localidad PRIMARY KEY CLUSTERED (ID)
)
GO


CREATE TABLE MANZANAS_MUESTRA
(
	COD14 NVARCHAR(14) NOT NULL,
)
GO
CREATE INDEX idx_manzanas_muestra ON dbo.MANZANAS_MUESTRA(COD14)


CREATE TABLE ZAT_LOCALIDAD
(
	ZAT INT NOT NULL,
	NLOCALIDAD NVARCHAR(2) NULL,
	ID_MUNICIPIO INT NOT NULL,
	LATITUD NUMERIC(20, 15) NULL,
	LONGITUD NUMERIC(20, 15) NULL,
	CONSTRAINT zat_localidad_pk PRIMARY KEY CLUSTERED (ZAT, ID_MUNICIPIO),
	CONSTRAINT fk_zat_localidad FOREIGN KEY (NLOCALIDAD) REFERENCES LOCALIDAD(ID)
)
GO
CREATE INDEX idx_zat_localidad ON dbo.ZAT_LOCALIDAD(NLOCALIDAD)
GO


CREATE TABLE MANZANAS_TOTAL
(
	ID NVARCHAR(14) NOT NULL,
	CODANE_DEPTO NVARCHAR(2) NULL,
	COD_MUNICIPIO NVARCHAR(3) NULL,
	CODANE NVARCHAR(5) NULL,
	ID_MUNICIPIO INTEGER NOT NULL,
	SECTOR INT NULL,
	SECCION INT NULL,
	MANZANA INT NULL,
	ZAT INT NOT NULL,
	MUESTRA INT NULL,
	LATITUD NUMERIC(20, 15) NULL,
	LONGITUD NUMERIC(20, 15) NULL,
	CONSTRAINT manzanas_total_pk PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT manzanas_total_zat_localidad_fk FOREIGN KEY (ZAT, ID_MUNICIPIO) REFERENCES dbo.ZAT_LOCALIDAD(ZAT, ID_MUNICIPIO)
)
GO
CREATE INDEX idx_manzanas_total ON dbo.MANZANAS_TOTAL(ZAT, ID_MUNICIPIO)
GO


CREATE TABLE NOEFECTIVAS
(
	ID_ENCUESTA INT NOT NULL,
	CONTACTO INT NOT NULL,
	RESULTADO INT NULL,
	CONSTRAINT id_noefectivas_pk PRIMARY KEY CLUSTERED (ID_ENCUESTA, CONTACTO),
	CONSTRAINT fk_noefectivas_encuestas FOREIGN KEY (ID_ENCUESTA) REFERENCES ENCUESTAS(ID_ENCUESTA)
)
GO


--Insert Values


CREATE TABLE INTERN_EXTERN_NAMES (rn INT, Intern NVARCHAR(100), Extern NVARCHAR(100))
INSERT INTO INTERN_EXTERN_NAMES
VALUES
(1, 'ACTIVIDAD', 'ACTIVIDAD.csv'),
(2, 'ACTIVIDADECONOMICA', 'ACTIVIDADECONOMICA.csv'),
(3, 'AGRESIONFISICA', 'AGRESIONFISICA.csv'),
(4, 'AGRESIONSEXUAL', 'AGRESIONSEXUAL.csv'),
(5, 'BENEFICIOSITP', 'BENEFICIOSITP.csv'),
(6, 'CONTACTOS', 'CONTACTOS.csv'),
(7, 'CULTURA', 'CULTURA.csv'),
(8, 'CURSOLICENCIA', 'CURSOLICENCIA.csv'),
(9, 'DEPARTAMENTO', 'DEPARTAMENTO.csv'),
(10, 'DISPONIBILIDAD_VEHICULOS', 'DISPONIBILIDAD_VEHICULOS.csv'),
(11, 'ENCUESTAS', 'ENCUESTAS_ANONIMIZADO.csv'),
(12, 'ETAPAS1', 'ETAPAS1.csv'),
(13, 'ETAPAS2', 'ETAPAS2.csv'),
(14, 'EXENTO_PP', 'EXENTO_PP.csv'),
(15, 'LICENCIACONDUCCION', 'LICENCIACONDUCCION.csv'),
(16, 'LIMITACIONFISICA', 'LIMITACIONFISICA.csv'),
(17, 'LOCALIDAD', 'LOCALIDAD.csv'),
(18, 'LUGARAGRESION', 'LUGARAGRESION.csv'),
(19, 'LUGARPARQUEO', 'LUGARPARQUEO.csv'),
(20, 'MANZANAS_MUESTRA', 'MANZANAS_MUESTRA.csv'),
(21, 'MANZANAS_TOTAL+ZAT_LOCALIDAD', 'MANZANAS_TOTAL+ZAT_LOCALIDAD.csv'),
(22, 'MANZANAS_TOTAL', 'MANZANAS_TOTAL.csv'),
(23, 'MEDIOTRASPORTE', 'MEDIOTRASPORTE.csv'),
(24, 'MEDIO_PREDOMINANTE', 'MEDIO_PREDOMINANTE.csv'),
(25, 'MOTIVONOVEHICULO', 'MOTIVONOVEHICULO.csv'),
(26, 'MOTIVOVIAJE', 'MOTIVOVIAJE.csv'),
(27, 'MUNICIPIO', 'MUNICIPIO.csv'),
(28, 'NIVELEDUCATIVO', 'NIVELEDUCATIVO.csv'),
(29, 'NOBICICLETA', 'NOBICICLETA.csv'),
(30, 'NOEFECTIVAS', 'NOEFECTIVAS.csv'),
(31, 'PARENTESCO', 'PARENTESCO.csv'),
(32, 'PERSONAS', 'PERSONAS_ANONIMIZADO.csv'),
(33, 'RANGOINGRESOS', 'RANGOINGRESOS.csv'),
(34, 'SEXO', 'SEXO.csv'),
(35, 'TIPOAGRESION', 'TIPOAGRESION.csv'),
(36, 'TIPOCOMBUSTIBLE', 'TIPOCOMBUSTIBLE.csv'),
(37, 'TIPOVEHICULO', 'TIPOVEHICULO.csv'),
(38, 'TIPOVIVIENDA', 'TIPOVIVIENDA.csv'),
(39, 'TRABAJOACTIVIDAD', 'TRABAJOACTIVIDAD.csv'),
(40, 'VEHICULOS', 'VEHICULOS.csv'),
(41, 'VIAJES1', 'VIAJES_ANONIMIZADOS1.csv'),
(42, 'VIAJES2', 'VIAJES_ANONIMIZADOS2.csv'),
(43, 'VIVIENDAPROPIA', 'VIVIENDAPROPIA.csv'),
(44, 'ZAT_LOCALIDAD', 'ZAT_LOCALIDAD.csv')
GO

CREATE PROCEDURE OBT_INT (@rn INT, @result1 NVARCHAR(100) OUTPUT)
AS
	SELECT @result1 = Intern FROM INTERN_EXTERN_NAMES WHERE rn = @rn
GO

CREATE PROCEDURE OBT_EXT (@rn INT, @result2 NVARCHAR(100) OUTPUT)
AS
	SELECT @result2 = Extern FROM INTERN_EXTERN_NAMES WHERE rn = @rn
GO


DECLARE @device_directory NVARCHAR(500)
DECLARE @n INT
DECLARE @i INT = 1
DECLARE @query_directory NVARCHAR(200)
DECLARE @bulk_insert NVARCHAR(1000)
DECLARE @external_source NVARCHAR(100)
DECLARE @internal_source NVARCHAR(100)


SELECT @n = COUNT(*) FROM INTERN_EXTERN_NAMES
SELECT @device_directory = SUBSTRING([filename], 1, CHARINDEX(N'BogTrPoll_DataBase\Database\BogTrPoll.mdf', LOWER([filename])) - 1) + N'BogTrPoll_CSV\'
FROM MASTER.DBO.SYSALTFILES
WHERE [name] = 'BogTrPoll'


WHILE @i <= @n  
	BEGIN
		EXEC OBT_EXT @i, @external_source OUTPUT
		EXEC OBT_INT @i, @internal_source OUTPUT
		SET @query_directory = @device_directory + @external_source
		SET @bulk_insert = 'BULK INSERT ' + @internal_source + ' FROM ''' + @query_directory + '''WITH ( FIRSTROW = 2, FIELDTERMINATOR ='';'', ROWTERMINATOR =''\n'' )'
		EXEC(@bulk_insert)
		
		SET @i = 1 + @i
	END
GO


CREATE PROCEDURE UNITE_TABLES (@Tab1 NVARCHAR(20), @Tab2 NVARCHAR(20), @Out_tab NVARCHAR(20))
AS
EXEC('INSERT INTO ' + @Out_Tab + ' SELECT * FROM ' + @Tab1 + ' UNION SELECT * FROM ' + @Tab2)
GO


EXEC UNITE_TABLES @Tab1 = 'ETAPAS1', @Tab2 = 'ETAPAS2', @Out_tab = 'ETAPAS'
EXEC UNITE_TABLES @Tab1 = 'VIAJES1', @Tab2 = 'VIAJES2', @Out_tab = 'VIAJES'


DROP PROCEDURE OBT_INT
DROP PROCEDURE OBT_EXT
DROP TABLE ETAPAS1
DROP TABLE ETAPAS2
DROP TABLE VIAJES1
DROP TABLE VIAJES2
